site_name: FIWARE IoT Broker
repo_url: https://github.com/Aeronbroker/Aeron.git
site_description: IoT Broker documentation
google_analytics: ['UA-83221735-1', 'http://fiware-iot-broker.readthedocs.io/en/master/']
docs_dir: doc
site_dir: html
markdown_extensions: [toc,fenced_code]
use_directory_urls: false
theme: readthedocs
extra_css: ["https://fiware.org/style/fiware_readthedocs.css"]
pages:
  - Home: 'index.md'
  - 'Installation and Administration Guide': 'installadminguide.md'
  - 'User and Developer Guide': 'userprogrammersguide.md'

  
